### ISSUE TITLE
VersionControl with Unity

### ISSUE THREAD

**Issue by Speednik2** [derElias/udvide-Client#2]
**Problem:**
Unity is not working with GitHub when pushing whole Folder.

**Task:**
Get the version Control working.

**Expected:**
Use the version control as it should(push, pull, commit).

**Comment by Speednik2** [comment]
Copied the whole Project to the FHWS Cloud to send it. 
After that i wrote an .gitignore that ignores the project file, some Libraries and the metadata from unity. 

Version Control is now working as it should!

**Comment by Siggi206** [comment]
couldn't push newly added files

**Comment by Speednik2** [comment]
Try using Gitext and a force push ! That works for me

**Comment by Speednik2** [comment]
We are using now Unity Collab.
